services:
  - type: web
    name: insightboard
    env: node
    build:
      command: npm install && npm run build
    start: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 7000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: TRAKT_CLIENT_ID
        sync: false
      - key: TRAKT_CLIENT_SECRET
        sync: false
      - key: TRAKT_REDIRECT_URI
        sync: false
      - key: BASE_URL
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
